"""empty message

Revision ID: 6e42925b10bc
Revises: 
Create Date: 2019-03-25 22:52:15.976011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e42925b10bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.Column('done_thing', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('object_id')
    )
    op.create_table('user',
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('object_id')
    )
    op.create_table('blog',
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.object_id'], ),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    op.drop_table('user')
    op.drop_table('record')
    # ### end Alembic commands ###
